# Generated by Django 3.0.5 on 2020-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('A_TEMPERATURE', 'Ambiental Temperature'), ('R_HUMIDITY', 'Relative Humidity'), ('B_PRESSURE', 'Barometric Presurre'), ('B_ALTITUDE', 'Barometric Altitude'), ('A_HUMIDITY', 'Barometric Humidity'), ('S_MOISTURE', 'Soil Moisture'), ('LDR_LIGHT', 'LDR Light Index')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('url_name', models.CharField(max_length=20)),
                ('snippet_title', models.CharField(max_length=30)),
                ('snippet_image', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiental', models.BooleanField()),
                ('sensor_type', models.CharField(choices=[('DHT11', 'Multisensor DHT11'), ('DHT22', 'Multisensor DHT22'), ('MCP9701A', 'Temperature sensor MCP9701A'), ('LDR', 'Photoresistor'), ('BME280', 'Pressure temperature altitude sensor BME280'), ('BMP180', 'Pressure temperature altitude sensor BMP180'), ('SM150', 'Moisture sensor'), ('CMS', 'Cable moisture sensor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
