# Generated by Django 3.0.5 on 2020-05-04 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IoT', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='access_keys',
            field=models.ManyToManyField(blank=True, related_name='token_iot_zones', to='users.CustomAccessTokens'),
        ),
        migrations.AddField(
            model_name='zones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_zones', to='IoT.Projects'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_sensors', to='IoT.Node'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_ambiental_sensors', to='IoT.Zones'),
        ),
        migrations.AddField(
            model_name='projects',
            name='access_keys',
            field=models.ManyToManyField(blank=True, related_name='token_iot_projects', to='users.CustomAccessTokens'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_iot_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='access_keys',
            field=models.ManyToManyField(blank=True, related_name='token_iot_nodes', to='users.CustomAccessTokens'),
        ),
        migrations.AddField(
            model_name='node',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_nodes', to='IoT.Zones'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_measurements', to='IoT.Sensors'),
        ),
    ]
